# Generated by Django 2.1 on 2019-03-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_create_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=25)),
                ('new_account_name', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_create_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_create_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_create_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_create_with_delegation_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=25)),
                ('new_account_name', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_create_with_delegation_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_create_with_delegation_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_create_with_delegation_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_update_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_update_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_update_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_update_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_proxy_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('proxy', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_proxy_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_proxy_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_proxy_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_vote_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('witness', models.CharField(max_length=25)),
                ('approve', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_vote_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('disapprove', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_vote_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('disapprove', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_witness_vote_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('disapprove', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='cancel_transfer_from_savings_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='cancel_transfer_from_savings_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='cancel_transfer_from_savings_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='cancel_transfer_from_savings_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='change_recovery_account_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_to_recover', models.CharField(max_length=25)),
                ('new_recovery_account', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='change_recovery_account_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='change_recovery_account_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='change_recovery_account_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='claim_rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('reward_steem', models.TextField(default='')),
                ('reward_sbd', models.TextField(default='')),
                ('reward_vests', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='claim_rewards_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField(default='')),
                ('sbd', models.TextField(default='')),
                ('vests', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='claim_rewards_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField(default='')),
                ('sbd', models.TextField(default='')),
                ('vests', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='claim_rewards_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField(default='')),
                ('sbd', models.TextField(default='')),
                ('vests', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('permlink', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_options_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('permlink', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_options_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_options_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_options_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='convert_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=25)),
                ('amount', models.TextField()),
                ('nai', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='convert_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='convert_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='convert_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_json_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_id', models.CharField(db_index=True, max_length=50)),
                ('json', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_json_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('follow', models.IntegerField()),
                ('unfollow', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_json_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('follow', models.IntegerField()),
                ('unfollow', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_json_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('follow', models.IntegerField()),
                ('unfollow', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delegate_vesting_shares_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegator', models.CharField(max_length=25)),
                ('delegatee', models.CharField(max_length=25)),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delegate_vesting_shares_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delegate_vesting_shares_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delegate_vesting_shares_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delete_comment_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('permlink', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delete_comment_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delete_comment_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='delete_comment_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_approve_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=25)),
                ('to_account', models.CharField(max_length=25)),
                ('agent', models.CharField(max_length=25)),
                ('who', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_approve_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_approve_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_approve_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_release_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=25)),
                ('to_account', models.CharField(max_length=25)),
                ('agent', models.CharField(max_length=25)),
                ('who', models.CharField(max_length=25)),
                ('receiver', models.CharField(max_length=25)),
                ('sbd', models.TextField()),
                ('steem', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_release_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_release_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_release_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_transfer_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=25)),
                ('to_account', models.CharField(max_length=25)),
                ('agent', models.CharField(max_length=25)),
                ('fee', models.TextField()),
                ('sbd', models.TextField()),
                ('steem', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_transfer_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('sbd', models.TextField()),
                ('steem', models.TextField()),
                ('fee', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_transfer_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('sbd', models.TextField()),
                ('steem', models.TextField()),
                ('fee', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_transfer_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('sbd', models.TextField()),
                ('steem', models.TextField()),
                ('fee', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='feed_publish_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='feed_publish_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='feed_publish_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='feed_publish_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_cancel_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_cancel_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_cancel_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_cancel_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_create_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=25)),
                ('amount', models.TextField()),
                ('nai', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_create_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_create_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit_order_create_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='recover_account_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_to_recover', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='recover_account_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='recover_account_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='recover_account_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='request_account_recovery_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_account', models.CharField(max_length=25)),
                ('account_to_recover', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='request_account_recovery_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='request_account_recovery_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='request_account_recovery_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='set_withdraw_vesting_route_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=25)),
                ('to_account', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='set_withdraw_vesting_route_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='set_withdraw_vesting_route_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='set_withdraw_vesting_route_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_from_savings_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_from', models.CharField(max_length=25)),
                ('value_to', models.CharField(max_length=25)),
                ('amount', models.TextField()),
                ('nai', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_from_savings_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_from_savings_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_from_savings_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_savings_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_from', models.CharField(max_length=25)),
                ('value_to', models.CharField(max_length=25)),
                ('amount', models.TextField()),
                ('nai', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_savings_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_savings_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_savings_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField()),
                ('sbd', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_vesting_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_from', models.CharField(max_length=25)),
                ('value_to', models.CharField(max_length=25)),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_vesting_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_vesting_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_to_vesting_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=25)),
                ('receiver', models.CharField(max_length=25)),
                ('amount', models.TextField(default='')),
                ('precision', models.TextField(default='')),
                ('nai', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfers_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField(default='')),
                ('sbd', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfers_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField(default='')),
                ('sbd', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfers_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('steem', models.TextField(default='')),
                ('sbd', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('permlink', models.TextField(default='')),
                ('weight', models.IntegerField()),
                ('value', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes_count_sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyses', models.CharField(db_index=True, max_length=10)),
                ('resolution', models.CharField(db_index=True, max_length=10)),
                ('data', models.TextField(default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_vesting_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_vesting_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_vesting_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_vesting_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='witness_update_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='witness_update_operation_count_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='witness_update_operation_count_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='witness_update_operation_count_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
