# Generated by Django 2.1 on 2019-03-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.TextField()),
                ('message', models.TextField()),
                ('function', models.TextField()),
                ('data', models.TextField()),
                ('block_num', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
