# Generated by Django 2.1 on 2019-02-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_claim_rewards_claim_rewards_count_day_claim_rewards_count_hour_claim_rewards_count_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim_rewards',
            name='reward_sbd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='claim_rewards',
            name='reward_steem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='claim_rewards',
            name='reward_vests',
            field=models.TextField(),
        ),
    ]
